[정찬욱] 자동차 경주 미션 Step1
fe-clean-code-study/js-racingcar-custom pull request #2
Opened 2024-06-21 08:13 UTC by seeyoujeong

### 미션을 수행하면서 어려웠던 점

- **테스트 작성**
처음 테스트 코드를 작성하다보니 방향성을 못잡은 코드가 완성됐습니다. 어떤 함수의 반환값이 boolean이면 일단 모든 경우에 해당하는 테스트 코드를 작성했습니다. 
- **액션(부수 효과가 있는 함수)을 가능한 작게 만들기**
main을 깔끔하게 작성하고 싶은 욕심에 암묵적 입력(readline)과 출력(console.log)을 제대로 분리하지 못했습니다. 어디까지 분리하는게 맞는지 모르겠네요.
- **클래스에 private, 정적 메소드 남발**
일단 제 기준에선 인스턴스 변수나 메소드를 사용하지 않으면 정적으로 만들었고 숨기고 싶으면 private로 선언했는데 테스트를 제대로 못하게 되는 문제가 있었습니다.

### 리뷰 받고 싶은 부분

- **Race 클래스**
  - private, 정적 키워드를 쓰는 기준이 맞는지.
  - 입력과 출력을 분리해야 하는지.
- **테스트 코드**
  - 전체적으로 작성하는 방법이 옳은지.
  - 테스트 설명은 어떤 문장으로 작성하면 좋은지.

### 궁금한 점

- 에러 메시지를 분리해서 관리하는 코드를 보다보면 일회성인 경우가 종종있어서 이게 분리하는게 맞는건지, 아니면 중복으로 사용하는 메시지만 분리해서 관리하는게 맞는건지 궁금합니다. 아니면 중복되는 부분, 예를 들어 "1자 이상이어야 합니다." 이부분을 활용해서 주어만 할당받아서 에러 메시지를 생성하는 함수를 만드는건 좋은 생각일까요?
- 테스트 코드를 짜면서 "기능을 리팩토링하고 제대로 실행되는지 확인하는 시간을 줄여주는 편리함이 있구나"를 느꼈는데, 테스트 코드 작성에 시간을 많이 투자하면 앞서 말한 장점이 퇴색되는 듯합니다. 테스트 코드 작성에 어느정도 투자하면 좋을지, 그리고 어디를 중점적으로 작성하면 좋을지 궁금합니다.

2024-06-22 10:05 UTC, JunilHwang requested changes
고생했어요 찬욱님!

여기서 요구사항이 변경되었을 때를 가정해보면 좋을 것 같아요 ㅎㅎ

1. 레이싱 경주의 규칙이 여러개면 어떻게 해야 좋을까?
2. 레이싱 경주의 규칙이 라운드마다 달라지면 어떻게 할 수 있을까?
3. 지금은 콘솔 기반의 어플리케이션인데, 웹 기반의 어플리케이션으로 변경된다면 도메인에서 어떤 부분을 재활용할 수 있을까?
4. 테스트 코드에서 경주의 결과를 예측하고 싶으면 어떻게 해야 좋을까?

이렇게 네 가지 포인트에 대해 고민을 해보시면 좋답니다!

2024-06-22 10:05 UTC, JunilHwang commented on src/domain/Car.js
> +class Car extends Racer {
Car가 Racer를 상속해서 사용할 때의 명확한 장점이 있을까요~?

2024-06-22 10:05 UTC, JunilHwang commented on src/domain/Race.js
> +class Race {
만약에 자동차 경주 게임이 콘솔이 아니라 웹에서 실행된다고 했을 떄, 이 클래스는 어떤 형태로 변형이 되어야 좋을까요?

반대로, 어떤 부분은 보존할 수 있을까요?

2024-06-22 10:05 UTC, JunilHwang commented on src/domain/Race.js
> +  }
이 부분은 도메인과 연관이 없는 것 같아요!

2024-06-22 10:05 UTC, JunilHwang commented on src/domain/Race.js
> +    if (4 <= number) racer.move();
여기서 쓰이는 숫자들은 다 상수로 만들어서 관리할 수 있지 않을까요!?

2024-06-22 10:05 UTC, JunilHwang commented on src/domain/Race.js
> +  }
지금은 레이싱 경기의 규칙이 "랜덤한 값"을 통해서 정해지고 있어요.
만약에 경주의 규칙이 달라진다거나 많아진다고 가정해보면 어떨까요?

극단적으로, 사용자가 규칙을 만들어서 경주에 주입할 수 있다면 어떨까요?

2024-06-22 10:05 UTC, JunilHwang commented on src/domain/Race.js
> +  }
혹은, 각각의 라운드마다 규칙이 달라진다면!?

2024-06-22 10:05 UTC, JunilHwang commented on src/service/readLineAsync.js
보통 서비스가 도메인을 의존하는 형태인데,
지금은 도메인이 서비스를 의존하고 있네요!

2024-06-22 10:05 UTC, JunilHwang commented on src/__tests__/Racer.test.js
> +});
외부에서 name이나 position을 변경할 수 있는지 테스트하는 코드도 있으면 좋아보이네요!

2024-06-22 10:05 UTC, JunilHwang commented on src/__tests__/Race.test.js
> +  });
제일 중요한게, 경기의 결과를 알 수 있는 방법이 없다는 것!
그렇다면 사이드 이펙트를 제대로 통제하고 있지 못하다는 이야기겠죠?

2024-06-22 10:13 UTC, JunilHwang reviewed
본문의 내용을 제가 제대로 못봤네요 ㅎㅎ

> private, 정적 키워드를 쓰는 기준이 맞는지.

대체로 잘 사용해주신 것 같아요!
테스트 때문에 private이 아니라 public으로 두는게 좋은 방법은 아니고, 현재 상황에서 어떻게 잘 테스트할 수 있을지 고민해보면 좋답니다 ㅎㅎ

> 입력과 출력을 분리해야 하는지.

제가 앞선 코멘트에 이야기했던 것 처럼 웹 기반의 어플리케이션으로 변경된다면 어떻게 코드가 수정될지 상상해보면서 분리해보세요!

> 전체적으로 작성하는 방법이 옳은지.

크게 잘못된부분은 없는 것 같아요 ㅎㅎ
대체로 잘 작성해주셨습니다.
다만 엣지케이스를 많이 작성해주는게 좋아요!

특히 실패하는 케이스에 대한 테스트를 먼저 작성하는게 제일 중요하답니다!

> 테스트 설명은 어떤 문장으로 작성하면 좋은지.

"A가 B를 하면 C가 된다."

저는 보통 이런식으로 작성하는 편이랍니다.

귀찮을땐...

"input: A, output: B"

이렇게 작성하기도 해요 ㅋㅋㅋ

테스트의 목적에 따라 많이 달라지는 것 같네요.
사용자의 UseCase 와 직접적인 연관이 있을 땐 시나리오를 설명하는 방식으로 스펙을 작성하고,
특정 함수의 input에 대한 output을 검증하고 싶을 때는 최대한 단순하게 작성합니다.

> 에러 메시지를 분리해서 관리하는 코드를 보다보면 일회성인 경우가 종종있어서 이게 분리하는게 맞는건지, 아니면 중복으로 사용하는 메시지만 분리해서 관리하는게 맞는건지 궁금합니다. 아니면 중복되는 부분, 예를 들어 "1자 이상이어야 합니다." 이부분을 활용해서 주어만 할당받아서 에러 메시지를 생성하는 함수를 만드는건 좋은 생각일까요?

꼭 중복이 발생하는 상황에서만 분리해야 하는건 아니라고 생각해요.
에러를 어디까지 전파하고 싶은지에 따라 다를 것 같은데,
가령 도메인에서 메세지를 구체화하게 되면 UI에서 에러를 표현하기가 힘들어요.
대신 에러 코드로 표현하고, 해당 에러 코드에 대해 UI에서 처리하도록 유도하면 조금 더 유연하게 사용할 수 있겠죠?

http status 같은 느낌이랄까..

저는 CustomError를 꽤 자주 사용했던 것 같네요!

> 테스트 코드를 짜면서 "기능을 리팩토링하고 제대로 실행되는지 확인하는 시간을 줄여주는 편리함이 있구나"를 느꼈는데, 테스트 코드 작성에 시간을 많이 투자하면 앞서 말한 장점이 퇴색되는 듯합니다. 테스트 코드 작성에 어느정도 투자하면 좋을지, 그리고 어디를 중점적으로 작성하면 좋을지 궁금합니다.

아직은 테스트 코드 작성이 익숙하지 않아서 그럴 수 있어요 ㅎㅎ
말씀해주신 것 처럼 시간을 꽤 많이 투자하게 되는데, 프로젝트 규모가 커질수록 테스트 코드가 발휘하는 힘이 무척 커요!

가령, 꽤 큰 규모의 프로젝트에 신입 개발자가 투입되었을 때 테스트코드가 없다면 신입 개발자는 개발을 할 때 너무나 큰 두려움을 느끼고 작은 기능을 하나 만들 때에도 시간이 엄청 오래 걸리겠죠?

그런데 신규 프로젝트에서는 테스트 코드가 그렇게까진 중요하지 않을 수 있어요.

상황에 따라 무척 다르답니다 ㅎㅎ
제일 좋은건 역시 항상 작성하는거지만, 일단 작성하는 연습이 제일 중요하지 않나 싶네요!

2024-06-22 12:33 UTC, seeyoujeong commented on src/service/readLineAsync.js
제가 이해하고 있는 **서비스**는 호스트 환경에서 사용하는 api(예. readline)를 가지고 만든 메서드를 포함하는 레이어고, **도메인**은 해당 애플리케이션의 기능을 포함하는 레이어로 이해하고 있습니다.
지금 코드는 서비스 레이어의 코드가 수정되면 도메인 레이어의 코드가 영향을 받는 형태이기 때문에 이 형태를 반대로 수정해야 서비스가 도메인을 의존하는 형태가 되겠군요.
의존에 대해 고민하다보니 궁극적으로는 최대한 결합도를 낮추기 위해 서비스와 도메인의 의존도도 낮추는 방향으로 코드를 설계하는게 좋은 생각의 방향일까요?

2024-06-22 14:20 UTC, JunilHwang commented on src/service/readLineAsync.js
음 저는 도메인이 런타임에 의존적이지 않은 모습이라고 생각했어요!

- 사이드 이펙트가 없어야 하고
- 런타임에 의존적이지 않아야하고
- 어플리케이션에 필요한 고유 개념들이 들어가있고

---


>  최대한 결합도를 낮추기 위해 서비스와 도메인의 의존도도 낮추는 방향

그니까 어플리케이션이 서비스와 도메인의 의존을 최소화 하는걸 말씀하시는거죠?
서비스의 의존은 낮추면 좋고 (혹은 한 곳에서 관리가 된다가 더 맞겠네요!)
도메인은 서비스에 전반적으로 쓰이는 핵심 재료라서 의존도를 낮추는건 쉽지 않아보이네요!

2024-06-22 14:38 UTC, seeyoujeong commented on src/service/readLineAsync.js
도메인의 기준과 의미를 제대로 정립할 필요가 있겠네요...

---

> 도메인은 서비스에 전반적으로 쓰이는 핵심 재료라서 의존도를 낮추는건 쉽지 않아보이네요!

위 문장에서 서비스는 어플리케이션을 의미하는건가요?

2024-06-23 04:32 UTC, jgjgill approved these changes
안녕하세요 찬욱님..!
데브코스에서는 따로 인연은 없었는데 이렇게 리뷰로 처음 인사드리게 되네요! 😆

빠르게 미션 올려주셔서 감사합니다..! 중간중간 참고하면서 많은 도움이 되었네요! 👍

> 에러 메시지를 분리

으음 이와 관련해서 리뷰로 남긴 부분에서 저는 상수로 구분하면 어떨지 라는 코멘트를 남겼네요.
이렇게 생각했던 이유는 해당 테스트에서 에러 메시지는 무조건 메서드에서 사용하는 에러 메시지와 동일해야 해서 그렇게 생각했던 것 같습니다..! 테스트 코드에서 메시지를 받는 형태로 안썼으면 분리까지 할 필요는 없을 것 같기도 하네요.

> 테스트 코드 관련

저도 익숙하지 않아서 많은 시간이 걸렸네요.. 🫠
그래서 저같은 경우 우선 코드 먼저 작성했습니다. ㅎㅎ 그다음에 테스트 코드를 작성하면서 코드의 잘못된 부분을 수정한 느낌?

이번 기회에 같이 학습하면서 테스트 코드와 친해지면서 빠르게 작성할 수 있게 되면 좋겠네요..!

어디를 중점적으로 작성하면 좋을지에 대해서는 저도 지금 한 번 해봤지만 왠지 하다보면 알게 될 것 같다는 느낌을 받았습니다..! 경험의 문제이지 않을까 싶네요! 😄

수고 많으셨습니다..! 🙇‍♂️

2024-06-23 04:32 UTC, jgjgill commented on src/__tests__/Race.test.js
> +        "경기 준비에 적합하지 않은 입력값입니다."
저같은 경우 에러 메시지가 도메인, 테스트에 동일하게 쓰이다 보니 상수로 구분했었네요..!

2024-06-23 04:32 UTC, jgjgill commented on src/domain/Race.js
> +  }
해당 메서드는 도메인과 뷰가 섞인 것 같다는 생각을 했습니다..!

현재 뷰와 관련된 메서드들은 접두사로 `show`가 붙은 것 같았는데요.
`progreessRace`도 뷰와 관련된 로직이 포함되어 있어보입니다! 🧐

2024-06-23 04:32 UTC, jgjgill commented on src/domain/Race.js
> +    return this.#racers.filter((racer) => racer.position === maxPosition);
`makeWinners`와 같은 함수로 구분해주면 더 명시적일 것 같아요..! 🤔

2024-06-23 04:32 UTC, jgjgill commented on src/domain/Race.js
> +  static #showResult(racers) {
저도 처음에는 이러한 `view` 로직을 `domain` 폴더에 포함시켰는데요.
테스트 코드를 작성하는 과정을 거치다 보니 도메인과 뷰를 분리하는 것의 필요성을 느끼게 되더라구요..! 😵

- 지금 `result`에서 `Race` 도메인에 관심있는 것은 레이서들의 이름만 관심있다?
- 테스트 코드에서 도메인을 가져올 때 뷰는 불필요하다?

지금은 도메인에 뷰와 관련된 메서드들이 포함되어 있다보니 변경을 어렵게 만들 수도 있겠다는 생각이 들었습니다..! 🙇‍♂️

2024-06-23 04:32 UTC, jgjgill commented on src/domain/Race.js
> +    const number = getRandomNumber(0, 9);
저같은 경우 `getRandomNumber`과 같은 전진 조건은 변경의 가능성이 많다고 생각했는데요!
그래서 의존성을 주입하는 형태?로 조건 코드를 구성했던 것 같아요..!
사용하는 쪽에서 조건을 설정하는 느낌?

2024-06-23 04:59 UTC, JunilHwang commented on src/service/readLineAsync.js
맞습니다!

2024-06-24 05:37 UTC, suyeon1218 reviewed
찬욱님 코드 보면서 제가 고찰했던 부분 (static, private) 에 대한 힌트를 얻어가요! 평소 문서를 엄청 꼼꼼하게 읽으셔서 그런지 `vitest` 관련 메서드를 엄청 다양하게 작성하신 게 인상 깊습니다 👍

2024-06-24 05:37 UTC, suyeon1218 commented on src/__tests__/Race.test.js
> +  });
궁금한 게 있습니다...! 지금은 랜덤값으로 경기 우승자가 결정되는데 결과를 알 수 있어야 한다는 건 둘 중 어느 쪽인가요...?! 아니면 둘다인가요? 🥲 

1. 경기를 임의로 조작해서 예상한 우승자가 나오는지 
2. 경기를 랜덤으로 진행해서 나온 우승자가 처음 전달한 자동차 이름 목록에 포함돼 있는지

2024-06-24 05:37 UTC, suyeon1218 commented on src/__tests__/Racer.test.js
> +  });
이런 게 있군용 `vitest` 문서를 좀 더 꼼꼼히 읽어봐야겠네요

2024-06-24 05:37 UTC, suyeon1218 commented on src/domain/Race.js
> +  }
특정 클래스에 종속되는 유효성 검사는 클래스 안에 넣어주는 게 하나의 방법일 수도 있겠네요...! 신기방기

2024-06-24 05:37 UTC, suyeon1218 commented on src/domain/Race.js
> +    }
이 코드도 validate~ 메서드로 분리할 수도 있을 것 같은데 따로 분리하지 않은 이유가 있나요?

2024-06-24 05:37 UTC, suyeon1218 commented on src/domain/Race.js
> +  }
`this.winners` 를 `showResult` 에서도 접근할 수 있을 것 같은데 매개변수로 전달하신 이유가 있을까요?

2024-06-24 05:37 UTC, suyeon1218 commented on src/domain/Race.js
> +      this.#addRacer(new this.#Racer(name));
1. `Main` 에서 전달하는 Car 클래스가 Racer 인자로 들어오는데 왜 Car 를 해당 파일에서 import 하지 않고 상위에서 전달해주나요?
2. 프라이빗 변수로 저장해서 생성자 함수를 사용하면 어떤 점이 좋나요...?!

2024-06-24 05:37 UTC, suyeon1218 commented on src/domain/Race.js
> +    const number = getRandomNumber(0, 9);
랜덤함수는 확실히 min max 의 범위가 달라질 가능성이 있겠네요!! 멋진 통찰이에요... 👍

2024-06-24 05:37 UTC, suyeon1218 commented on src/domain/Car.js
> +class Car extends Racer {
지금은 자동차=레이서라서 자동차 클래스가 Racer 클래스와 합쳐져도 될 것 같은데 레이서가 자동차가 아니라 다른 경우를 고려할 수 있을 것 같아요! 동물 레이싱이라든지...? 🦒

2024-06-24 05:37 UTC, suyeon1218 commented on src/domain/Racer.js
> +  }
궁금한 게 있는데 Racer 를 상속해서 쓸수 있다고 하면 Racer 에는 따로 유효성 검사를 하지 않아도 되나요?

2024-06-24 05:37 UTC, suyeon1218 commented on src/utils/isSubclass.js
이런 식으로 서브클래스를 검사하는군요 신기방기... 잘 배워갑니다

2024-06-25 02:14 UTC, seeyoujeong commented on src/domain/Race.js
> +  }
뷰를 분리해야겠군요!

2024-06-25 02:36 UTC, seeyoujeong commented on src/domain/Car.js
> +class Car extends Racer {
`Racer` 클래스를 상속받는 클래스는 `Race`에 참여할 수 있게 해주고싶어서 `Racer` 클래스를 만들었습니다!
왜냐하면 `Race` 클래스 내부에서 `Racer`의 메서드나 프로퍼티를 사용하다보니 규칙(?)같은 걸 만들면 편하겠다 싶었거든요 ㅎㅎ

2024-06-25 02:38 UTC, seeyoujeong commented on src/domain/Race.js
> +class Race {
입력과 출력 부분을 분리하고 경주에 필요한 데이터와 메서드만 남기면 역할 분리를 할 수 있습니다!

2024-06-25 02:39 UTC, seeyoujeong commented on src/domain/Race.js
> +  }
입력 부분 도려내기 하겠습니다 ㅎㅎ

2024-06-25 02:42 UTC, seeyoujeong commented on src/__tests__/Race.test.js
> +  });
Race 클래스의 출력 부분을 분리하고 경기 결과를 기록하고 반환하는 기능을 추가해야겠군요!

2024-06-25 02:45 UTC, seeyoujeong commented on src/domain/Race.js
> +  }
찾기 편한 장점은 있는 것 같아요!

2024-06-25 02:46 UTC, seeyoujeong commented on src/domain/Race.js
> +    }
ㅎㅎ... 미스랄까요..?! 수정하러 갑니다!

2024-06-25 02:49 UTC, seeyoujeong commented on src/domain/Race.js
> +  }
정적 메서드로 만들면 메모리 공간을 절약할 수 있는걸로 알고있어요..! 
정적 메서드는 인스턴스 프로퍼티를 참조할 수 없다보니 매개변수로 전달한거죠!

2024-06-25 02:55 UTC, seeyoujeong commented on src/domain/Race.js
> +      this.#addRacer(new this.#Racer(name));
> Main 에서 전달하는 Car 클래스가 Racer 인자로 들어오는데 왜 Car 를 해당 파일에서 import 하지 않고 상위에서 전달해주나요?

Race 클래스에서 Car 클래스를 import하지 않고 인수로 넘겨주는 이유를 물어보시는건가요...?

> 프라이빗 변수로 저장해서 생성자 함수를 사용하면 어떤 점이 좋나요...?!

외부에서 수정 못하게 하려고 프라이빗 변수로 저장했어요!

2024-06-25 02:56 UTC, seeyoujeong commented on src/domain/Racer.js
> +  }
흠 뭔가 상속받는 클래스에게 유효성 검사의 역할을 주고 싶었어요!

2024-06-25 02:58 UTC, seeyoujeong commented on src/__tests__/Race.test.js
> +        "경기 준비에 적합하지 않은 입력값입니다."
수정하다보니 동일하게 쓰는 메시지가 생겨서 저도 분리해야겠네요 ㅎㅎ

2024-06-25 03:00 UTC, seeyoujeong commented on src/domain/Race.js
> +  static #showResult(racers) {
맞습니다... 뷰랑 같이 있다보니 테스트 코드 작성이 어렵더라구요... 그래서 저도 분리했습니다!

2024-06-25 05:17 UTC, suyeon1218 commented on src/domain/Race.js
> +      this.#addRacer(new this.#Racer(name));
> Race 클래스에서 Car 클래스를 import하지 않고 인수로 넘겨주는 이유를 물어보시는건가요...?

네 맞습니다! 제가 식견이 부족해서... 특정 패턴이 있나 궁금했어요!

2024-06-25 10:09 UTC, hyoribogo approved these changes
찬욱님 안녕하세요, 이렇게 스터디로 같이 함께해서 너무 영광입니다 !! 😸 
빠르게 PR 올려주셔서 저도 자극 받아서 빨리 할 수 있었어요 감사합니당ㅎㅎㅎ

> private, 정적 키워드

저는 사실 작성하면서도 "왜" 분리해서 쓰는지 제대로는 이해 못했었어요. 그래서 gpt한테 물어보면서 작성했었는데 메모리 공간 절약에 대해서는 처음 알았어요! 매개변수로 전달하는 방법도 미처 생각 못했던 부분이라 그냥 프로토타입 메서드로 작성했었는데, 참고해서 변경해봐야겠어요! 감사합니당


> 테스트 코드

저는 처음에 test('~~~한다.') 만 작성하고 기능을 구현했는데, 이 순서도 꽤 괜찮았던 것 같아요! 그리고 준일 멘토님이 말씀하셨던 것처럼 실패하는 케이스나 엣지 케이스를 먼저 고려해보는 것도 좋은 방법인 것 같아요!!!

---
전체적으로 깔끔하게 작성해주셔서 편하게 읽을 수 있었습니다! 그리고 관심사 분리에 대한 정보 공유도 감사드립니다 👍🏻 👍🏻👍🏻

2024-06-25 10:09 UTC, hyoribogo commented on src/__tests__/Race.test.js
> +        "경기 준비에 적합하지 않은 입력값입니다."
아하 이렇게 에러메시지도 검사할 수 있군요!

2024-06-25 10:09 UTC, hyoribogo commented on src/utils/getRandomNumber.js
문자열이나 다른 값들을 입력했을 때 처리도 있으면 좋을 것 같아요!

2024-06-25 10:09 UTC, hyoribogo commented on src/domain/Racer.js
> +  }
그럼 추상 메서드로 작성해놔도 좋을 것 같아요. tanstack query에서도 [Subscribable 클래스](https://github.com/TanStack/query/blob/main/packages/query-core/src/subscribable.ts)에 이런 식으로 작성해놓은 게 있더라고요!

```js
static validateName() {
  // Do nothing
}
```

2024-06-25 10:09 UTC, hyoribogo commented on src/domain/Car.js
> +class Car extends Racer {
저도 사람이나 동물들도 고려했다가 Vehicle에 상속 받았는데, Racer를 쓰면 더 범용적으로 받을 수 있겠군요 !!

2024-06-25 10:09 UTC, hyoribogo commented on src/utils/getRandomNumber.js
> +  return Math.floor(Math.random() * (max - min + 1)) + min;
헉 이렇게 간결하게 작성할 수도 있군요.. !! 전 음수랑 양수랑 다르게 나와서 케이스를 분리했는데, floor를 사용하면 간단하게 구할 수 있군요 👍🏻

2024-06-25 10:09 UTC, hyoribogo commented on src/utils/deepCopy.js
Map이나 Set 객체들을 넣으면 원하는 값이 나오지 않아서,
배열이나 Object만 copy하는 함수로 표현하거나 다른 객체들도 고려하면 좋을 것 같습니다!

2024-06-25 12:02 UTC, seeyoujeong commented on src/domain/Race.js
> +      this.#addRacer(new this.#Racer(name));
아 그 이유는 import를 한다는거 자체가 의존성이 생긴다고 생각을해서 Car 클래스라는 덜 추상적인 클래스를 import하지 않고 Racer 클래스로 추상화해서 인수로 넘겨주는 방식을 택한거에요!

2024-06-25 12:05 UTC, seeyoujeong commented on src/utils/getRandomNumber.js
놓친 부분 피드백 감사합니다!

2024-06-25 12:06 UTC, seeyoujeong commented on src/utils/deepCopy.js
맞아요.. ㅎㅎ 함수명을 좀 수정하거나 예외처리를 추가해야겠네요!

2024-06-26 04:24 UTC, merged