[이종길] 자동차 경주 미션 Step1
fe-clean-code-study/js-racingcar-custom pull request #4
Opened 2024-06-22 18:08 UTC by jgjgill

자세한 내용은 아침에 작성 예정.. 😇

<img width="600" alt="자동차 경주 구조도" src="https://github.com/fe-clean-code-study/js-racingcar-custom/assets/79239852/cdd689ef-83dd-4c4a-b9f3-c516ae5433b3">

- `자동차`와 `경주`로 도메인 구성
- 두 도메인을 연결해주는 `Target`에서 추상 클래스의 필요성, 프로토타입으로도 가능한 것 같은데 복잡... JSDoc 으로 대체해봄
- 테스트 코드를 작성해보니 view 관심사 분리의 필요성을 느낌, 이번에 크게 배운 부분..!
- 테스트 코드에서 반복되는 코드 없앨 수 있을 것 같은데.. 학습해 나갈 부분..!

### 미션을 수행하면서 어려웠던 점

### 리뷰 받고 싶은 부분

### 궁금한 점

2024-06-22 18:10 UTC, jgjgill commented on src/domain/race.js
> +  function play({ distance = 1, moveView, moveResultView }) {
`moveView`, `moveResultView`을 구성하면서 상태의 필요성을 느낌..! 🧐

2024-06-23 06:03 UTC, JunilHwang requested changes
미션을 통해 무수히 많은 고민을 한게 느껴지네요 ㅎㅎ

아마 함수를 기반으로 만들어가는게 쉽지 않았을 것 같아요.
사실 쓰이는 모습을 보면 순수 함수로만 구성된게 아니라, class를 사용하지 않기 위한 과정들이 많이 보인달까... 그렇네요

---

> 규칙이 추가되면 isValidMove과 같은 조건 파라미터를 추가하면 대처가 가능하지 않을까 싶은데..
더 좋게 구성할 수 있는 방법이 있는지 알고 싶네요.. 😅

인자에 대한 고민을 하기 시작하면 끝이 없는 것 같아요 ㅋㅋ

이게 실무에서도 많이 하는 고민인데, "어디까지 열어줄꺼야?" "너무 오버엔지니어링 아니야?" 와 이어지는 것들 같아요.

적정 수준에서 끊어내는게 무척 중요하답니다!
하지만 끊어내기 위해선 일단 멀리 가보는게 중요해요.
고민이 많이 된다면, 할 수 있는 최대한의 오버엔지니어링을 해보고 "아 이정도까진 필요없구나" 를 느끼는 지점을 찾아내어야 할 것 같아요.

그래서 저는 학습을 할 때는 꽤 극단적인 시도가 필요하다고 생각한답니다!

> 해당 부분을 잘했는지 저 스스로는 객관적으로 잘 판단이 안되네요. (잘하고 있는게 맞나?)

이미 지금과 같은 고민을 하는 것 자체가 잘 하고 있다는 이야기라고 생각해요.
대신 그 고민을 코드로 계속 풀어낼 수 있으면 훨씬 좋지 않을까 싶습니다 ㅎㅎ
이렇게도 해보고 저렇게도 해보는거죠!

저같은경우 똑같은 내용에 대해 (가령 TodoList 라거나...) 정말 많은 방법으로 코드를 작성했었어요.

클래스 기반으로도 작성해보고
함수 기반으로도 작성해보고
타입스크립트로도 작성해보고
프레임워크를 사용해서 만들어보기도 하고
막 만들어보기도 하고

기타 등등!

그러다보면 자연스럽게 내가 어떤 스타일을 좋아하는지, 왜 그걸 추구하는지 알게 되고 깊게 파고들어갈 수 있다고 생각해요.

---

일단 리뷰에 남긴 내용 대부분은 자잘한 것들이고 제일 핵심적인게  "domain이 view에 대해 간접적으로 의존하고 있는 부분"입니다.

이건 끊어내는게 좋을 것 같아요!

2024-06-23 06:03 UTC, JunilHwang commented on src/util/validation.js
> +export const ERROR_NAME_LABEL = "이름은 5자 이하만 가능합니다.";
유틸보단 도메인과 가까운 변수들 같아요!
유틸은 "도메인에 종속적이지 않은 것"이 모여있어야 하지 않을까요!?

2024-06-23 06:03 UTC, JunilHwang commented on src/domain/car.js
> +  return { setMovement, getNow, getName };
```suggestion
  function getNow() {
    return now;
  }

  function getName() {
    return name;
  }

  return { setMovement, get now(){ return now }, get name() { return name } };
```
이렇게 getter로 표현하는 방법도 있답니다!

2024-06-23 06:03 UTC, JunilHwang commented on src/domain/car.js
> +  }
set 이라고 하기에는 값을 증가시키는거라서
`incrementMovement ` 처럼 표현하면 어떨까요!?
혹은 아예 추상화를 해서 `move` 처럼 표현하는것도 좋을 것 같아요!

2024-06-23 06:03 UTC, JunilHwang commented on src/domain/race.js
> +function makewinnerNow(acc, target) {
```suggestion
function makeWinnerNow(acc, target) {
```

이렇게 해야 자연스러울 것 같아요!

2024-06-23 06:03 UTC, JunilHwang commented on src/domain/race.js
> +}
```suggestion
function makeWinners(targets, winnerMovement) {
  return targets
    .filter((target) => target.getNow() === winnerMovement)
    .map((target) => target.getName());
}
```
max 보단 조금 구체적으로 표현해주면 어떨까 싶어요!

2024-06-23 06:03 UTC, JunilHwang commented on src/domain/race.js
> +}
이 부분이 make보다는 find 로 표현되면 어떨까 싶어요!
```suggestion
function findWinnerMovement(targets) {
  return Math.max(...targets.map(target => target.getNow()));
}
```

이런식으로!?

2024-06-23 06:03 UTC, JunilHwang commented on src/domain/race.js
> +        moveOrStop({ target, distance, rule: isValidMove, moveView })
이 부분도 별도의 함수로 분리해주면 어떨까 싶어요!

2024-06-23 06:03 UTC, JunilHwang commented on src/domain/race.js
> +      moveView(name);
domain이 view의 존재를 알고 있어야 좋을까요~?

가령 MVC 패턴을 통해서 생각해보면

Model은 View나 Controller의 존재를 아예 모르고 있고,
Controller가 Model을 받아와서 무언가 처리를 한 다음에 View에게 전달해준답니다!

지금은 거꾸로 View의 내용을 model에 전달하는 모습이라서 약간... 어색해요!

2024-06-23 06:03 UTC, JunilHwang commented on src/view/race.js
> +    console.log(`꽁꽁 얼어붙은 한강 위로 ${name}가 전진합니다`);
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ 빵터졌네요

2024-06-23 06:03 UTC, JunilHwang commented on src/__tests__/car.test.js
> +    expect(car.getNow()).toBe(100);
```suggestion
  it("이동한 값만큼 현재 위치가 변경됩니다.", () => {
    const car = Car("제네시스");
    car.setMovement(100);
    car.setMovement(100);

    expect(car.getNow()).toBe(100);
```

아마 이렇게 사용했을 때 
사람들이 예상하는 출력값은 100이지만
실제로는 200이 나오게 되지 않을까 싶네요!

2024-06-23 06:03 UTC, JunilHwang commented on src/__tests__/race.test.js
> +  );
소숫점이면 어떻게 되나요!?

2024-06-24 13:03 UTC, seeyoujeong reviewed
클래스가 아닌 함수로 구현하셔서 재밌게 읽었습니다!
저도 테스트할 때 mock을 한번 써봐야겠네요 ㅎㅎ

2024-06-24 13:03 UTC, seeyoujeong commented on src/__tests__/car.test.js
> +  it("현재 위치를 수정할 수 있습니다.", () => {
"초기 위치를 지정할 수 있습니다." 가 좀더 명확할 것 같아요!

2024-06-24 13:03 UTC, seeyoujeong commented on src/domain/race.js
> +}
`makeWinners`보단 `findWinners`가 좋을 것 같아요!

2024-06-24 14:24 UTC, jgjgill commented on src/util/validation.js
> +export const ERROR_NAME_LABEL = "이름은 5자 이하만 가능합니다.";
네넵 맞는 것 같습니다..! 🤔

ef7a35b5268d90970395d28eacf8c82bb5014eae

2024-06-24 14:38 UTC, jgjgill commented on src/domain/car.js
> +  return { setMovement, getNow, getName };
오오 한 번 적용해보면서 빠르게 문서 읽어봤습니다..! 👍 

[프로퍼티 getter와 setter](https://ko.javascript.info/property-accessors#ref-885)

910db530c48e105a7bf8419ff65b18bfa45fdad9

2024-06-24 14:39 UTC, jgjgill commented on src/domain/race.js
> +function makewinnerNow(acc, target) {
아이고.. 이런 실수를.. 😵

be5e054d3db09a25b94b18da223af45cd4d3d117

2024-06-24 14:46 UTC, jgjgill commented on src/domain/race.js
> +}
> max 보단 조금 구체적으로 표현해주면 어떨까 싶어요!

너무 추상적이였네요..! 감사합니다!

> makeWinners보단 findWinners가 좋을 것 같아요!

다른 함수도 `make`로 하다보니 일관성을 유지하려고 `makeWinners`로 했던 것 같네요..!
말씀대로 `findWinners`가 더 적절해보입니다. 감사합니다! 

7c878ad1ba6d8e24d0016dd7b38b90d879e49624

2024-06-24 14:51 UTC, jgjgill commented on src/domain/car.js
> +  }
아아 밑에 테스트 코드 말씀하신 부분에서 확 와닿았습니다..! 감사합니다! 🙇‍♂️

cb54b72a7df07267783a7956a8de148708875752

2024-06-24 14:51 UTC, jgjgill commented on src/__tests__/car.test.js
> +    expect(car.getNow()).toBe(100);
위에 리뷰에서 확인한 사항!

cb54b72a7df07267783a7956a8de148708875752

2024-06-24 14:55 UTC, jgjgill commented on src/__tests__/race.test.js
> +  );
에러를 발생시킵니다..! 테스트 추가하기!

7c878ad1ba6d8e24d0016dd7b38b90d879e49624

2024-06-24 14:55 UTC, jgjgill commented on src/__tests__/car.test.js
> +  it("현재 위치를 수정할 수 있습니다.", () => {
오오 감사합니다..! 🙇‍♂️

2a1c32e73ac29818dd833621f458aa7110764f51

2024-06-24 15:32 UTC, jgjgill commented on src/domain/race.js
> +      moveView(name);
화요일날 해결하기.. 😵

2024-06-24 15:32 UTC, jgjgill commented on src/domain/race.js
> +        moveOrStop({ target, distance, rule: isValidMove, moveView })
화요일날 해결하기.. 😵

2024-06-25 05:11 UTC, suyeon1218 reviewed
안녕하세요 종길님...! 코드 리뷰를 드리는 건 처음이네요...! 잘 부탁드립니다! 

코드를 보며 읽기 쉽다는 생각을했어요. 그리고 종길님이 어떻게 해야 View 와 도메인 로직을 분리할 수 있을지 나름대로 고민하시고, 또 코드에 많은 관심을 기울인 게 느껴집니다. 도메인/비즈니스 로직에 대한 견해가 많이 부족해서 변수명과 같은 부분밖에 캐치하지 못하고 오히려 종길님의 PR 을 보며 배우기만 한 것 같네요...! 😓 고생 많으셨습니다!

2024-06-25 05:11 UTC, suyeon1218 commented on src/view/race.js
> +    console.log(`꽁꽁 얼어붙은 한강 위로 ${name}가 전진합니다`);
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ얼결에 이 파일부터 클릭해서 봤는데 ㅋㅋㅋㅋㅋㅋㅋㅋ

2024-06-25 05:11 UTC, suyeon1218 commented on src/util/validation.js
파일 이름만 본다면 유효성 검사함수를 여기 모아놓은 것처럼 보여요!

2024-06-25 05:11 UTC, suyeon1218 commented on src/main.js
> +    race.play({ moveView, moveResultView });
Race 에서 라운드가 진행될 때 마다 View 를 호출하도록 했군요...! 도메인 에선 뷰에 대한 정보를 몰라야 한다곤 하지만 이런 방법도 있다는 걸 알아가요!

2024-06-25 05:11 UTC, suyeon1218 commented on src/domain/car.js
> +  }
별건 아니지만 distance 에 defaultValue 를 넣어주면 더 편리할 것 같아요!

2024-06-25 05:11 UTC, suyeon1218 commented on src/domain/race.js
> +      moveView(name);
저도 한 번 깊게 고민해봐야겠네요...!

2024-06-25 05:11 UTC, suyeon1218 commented on src/domain/race.js
> +  function moveOrStop({ target, distance = 1, rule, moveView }) {
`stop` 이라는 함수명이 뭔가 함수에서 자동차를 멈추는 동작도 하나? 라는 느낌도 들게 하는 것 같아요!

2024-06-25 10:48 UTC, jgjgill commented on src/main.js
> +    race.play({ moveView, moveResultView });
아아 야매(?)라고 할 수 있을 것 같기도.. (안 좋은 예시로 생각해도 좋을 것 같아요..!)
제가 봤을 때 해당 부분이 핵심이긴 하네요! 🧐

지금 코드는 **강한 의존성을 약하게 의존하는 형태**로 변경했다고 생각합니다.
이것을 어떻게 끊어내는지가 정말 중요한 것 같더군요..!

2024-06-26 04:24 UTC, merged